import 'package:flutter/foundation.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

/// Available types for a [Place]
///
/// Ref: https://developers.google.com/maps/documentation/places/android-sdk/supported_types
enum PlaceType {
  @JsonValue('other')
  OTHER,
  @JsonValue('accounting')
  ACCOUNTING,
  @JsonValue('administrative_area_level_1')
  ADMINISTRATIVE_AREA_LEVEL_1,
  @JsonValue('administrative_area_level_2')
  ADMINISTRATIVE_AREA_LEVEL_2,
  @JsonValue('administrative_area_level_3')
  ADMINISTRATIVE_AREA_LEVEL_3,
  @JsonValue('administrative_area_level_4')
  ADMINISTRATIVE_AREA_LEVEL_4,
  @JsonValue('administrative_area_level_5')
  ADMINISTRATIVE_AREA_LEVEL_5,
  @JsonValue('airport')
  AIRPORT,
  @JsonValue('amusement_park')
  AMUSEMENT_PARK,
  @JsonValue('aquarium')
  AQUARIUM,
  @JsonValue('archipelago')
  ARCHIPELAGO,
  @JsonValue('art_gallery')
  ART_GALLERY,
  @JsonValue('atm')
  ATM,
  @JsonValue('bakery')
  BAKERY,
  @JsonValue('bank')
  BANK,
  @JsonValue('bar')
  BAR,
  @JsonValue('beauty_salon')
  BEAUTY_SALON,
  @JsonValue('bicycle_store')
  BICYCLE_STORE,
  @JsonValue('book_store')
  BOOK_STORE,
  @JsonValue('bowling_alley')
  BOWLING_ALLEY,
  @JsonValue('bus_station')
  BUS_STATION,
  @JsonValue('cafe')
  CAFE,
  @JsonValue('campground')
  CAMPGROUND,
  @JsonValue('car_dealer')
  CAR_DEALER,
  @JsonValue('car_rental')
  CAR_RENTAL,
  @JsonValue('car_repair')
  CAR_REPAIR,
  @JsonValue('car_wash')
  CAR_WASH,
  @JsonValue('casino')
  CASINO,
  @JsonValue('cemetery')
  CEMETERY,
  @JsonValue('church')
  CHURCH,
  @JsonValue('city_hall')
  CITY_HALL,
  @JsonValue('clothing_store')
  CLOTHING_STORE,
  @JsonValue('colloquial_area')
  COLLOQUIAL_AREA,
  @JsonValue('continent')
  CONTINENT,
  @JsonValue('convenience_store')
  CONVENIENCE_STORE,
  @JsonValue('country')
  COUNTRY,
  @JsonValue('courthouse')
  COURTHOUSE,
  @JsonValue('dentist')
  DENTIST,
  @JsonValue('department_store')
  DEPARTMENT_STORE,
  @JsonValue('doctor')
  DOCTOR,
  @JsonValue('drugstore')
  DRUGSTORE,
  @JsonValue('electrician')
  ELECTRICIAN,
  @JsonValue('electronics_store')
  ELECTRONICS_STORE,
  @JsonValue('embassy')
  EMBASSY,
  @JsonValue('establishment')
  ESTABLISHMENT,
  @JsonValue('finance')
  FINANCE,
  @JsonValue('fire_station')
  FIRE_STATION,
  @JsonValue('floor')
  FLOOR,
  @JsonValue('florist')
  FLORIST,
  @JsonValue('food')
  FOOD,
  @JsonValue('funeral_home')
  FUNERAL_HOME,
  @JsonValue('furniture_store')
  FURNITURE_STORE,
  @JsonValue('gas_station')
  GAS_STATION,
  @JsonValue('general_contractor')
  GENERAL_CONTRACTOR,
  @JsonValue('geocode')
  GEOCODE,
  @JsonValue('grocery_or_supermarket')
  GROCERY_OR_SUPERMARKET,
  @JsonValue('gym')
  GYM,
  @JsonValue('hair_care')
  HAIR_CARE,
  @JsonValue('hardware_store')
  HARDWARE_STORE,
  @JsonValue('health')
  HEALTH,
  @JsonValue('hindu_temple')
  HINDU_TEMPLE,
  @JsonValue('home_goods_store')
  HOME_GOODS_STORE,
  @JsonValue('hospital')
  HOSPITAL,
  @JsonValue('insurance_agency')
  INSURANCE_AGENCY,
  @JsonValue('intersection')
  INTERSECTION,
  @JsonValue('jewelry_store')
  JEWELRY_STORE,
  @JsonValue('laundry')
  LAUNDRY,
  @JsonValue('lawyer')
  LAWYER,
  @JsonValue('library')
  LIBRARY,
  @JsonValue('light_rail_station')
  LIGHT_RAIL_STATION,
  @JsonValue('liquor_store')
  LIQUOR_STORE,
  @JsonValue('local_government_office')
  LOCAL_GOVERNMENT_OFFICE,
  @JsonValue('locality')
  LOCALITY,
  @JsonValue('locksmith')
  LOCKSMITH,
  @JsonValue('lodging')
  LODGING,
  @JsonValue('meal_delivery')
  MEAL_DELIVERY,
  @JsonValue('meal_takeaway')
  MEAL_TAKEAWAY,
  @JsonValue('mosque')
  MOSQUE,
  @JsonValue('movie_rental')
  MOVIE_RENTAL,
  @JsonValue('movie_theater')
  MOVIE_THEATER,
  @JsonValue('moving_company')
  MOVING_COMPANY,
  @JsonValue('museum')
  MUSEUM,
  @JsonValue('natural_feature')
  NATURAL_FEATURE,
  @JsonValue('neighborhood')
  NEIGHBORHOOD,
  @JsonValue('night_club')
  NIGHT_CLUB,
  @JsonValue('painter')
  PAINTER,
  @JsonValue('park')
  PARK,
  @JsonValue('parking')
  PARKING,
  @JsonValue('pet_store')
  PET_STORE,
  @JsonValue('pharmacy')
  PHARMACY,
  @JsonValue('physiotherapist')
  PHYSIOTHERAPIST,
  @JsonValue('place_of_worship')
  PLACE_OF_WORSHIP,
  @JsonValue('plumber')
  PLUMBER,
  @JsonValue('plus_code')
  PLUS_CODE,
  @JsonValue('point_of_interest')
  POINT_OF_INTEREST,
  @JsonValue('police')
  POLICE,
  @JsonValue('political')
  POLITICAL,
  @JsonValue('post_box')
  POST_BOX,
  @JsonValue('post_office')
  POST_OFFICE,
  @JsonValue('postal_code_prefix')
  POSTAL_CODE_PREFIX,
  @JsonValue('postal_code_suffix')
  POSTAL_CODE_SUFFIX,
  @JsonValue('postal_code')
  POSTAL_CODE,
  @JsonValue('postal_town')
  POSTAL_TOWN,
  @JsonValue('premise')
  PREMISE,
  @JsonValue('primary_school')
  PRIMARY_SCHOOL,
  @JsonValue('real_estate_agency')
  REAL_ESTATE_AGENCY,
  @JsonValue('restaurant')
  RESTAURANT,
  @JsonValue('roofing_contractor')
  ROOFING_CONTRACTOR,
  @JsonValue('room')
  ROOM,
  @JsonValue('route')
  ROUTE,
  @JsonValue('rv_park')
  RV_PARK,
  @JsonValue('school')
  SCHOOL,
  @JsonValue('secondary_school')
  SECONDARY_SCHOOL,
  @JsonValue('shoe_store')
  SHOE_STORE,
  @JsonValue('shopping_mall')
  SHOPPING_MALL,
  @JsonValue('spa')
  SPA,
  @JsonValue('stadium')
  STADIUM,
  @JsonValue('storage')
  STORAGE,
  @JsonValue('store')
  STORE,
  @JsonValue('street_address')
  STREET_ADDRESS,
  @JsonValue('street_number')
  STREET_NUMBER,
  @JsonValue('sublocality_level_1')
  SUBLOCALITY_LEVEL_1,
  @JsonValue('sublocality_level_2')
  SUBLOCALITY_LEVEL_2,
  @JsonValue('sublocality_level_3')
  SUBLOCALITY_LEVEL_3,
  @JsonValue('sublocality_level_4')
  SUBLOCALITY_LEVEL_4,
  @JsonValue('sublocality_level_5')
  SUBLOCALITY_LEVEL_5,
  @JsonValue('sublocality')
  SUBLOCALITY,
  @JsonValue('subpremise')
  SUBPREMISE,
  @JsonValue('subway_station')
  SUBWAY_STATION,
  @JsonValue('supermarket')
  SUPERMARKET,
  @JsonValue('synagogue')
  SYNAGOGUE,
  @JsonValue('taxi_stand')
  TAXI_STAND,
  @JsonValue('tourist_attraction')
  TOURIST_ATTRACTION,
  @JsonValue('town_square')
  TOWN_SQUARE,
  @JsonValue('train_station')
  TRAIN_STATION,
  @JsonValue('transit_station')
  TRANSIT_STATION,
  @JsonValue('travel_agency')
  TRAVEL_AGENCY,
  @JsonValue('university')
  UNIVERSITY,
  @JsonValue('veterinary_care')
  VETERINARY_CARE,
  @JsonValue('zoo')
  ZOO,
}

final placeTypeValuesMap = Map.fromIterable(PlaceType.values,
    key: (item) => describeEnum(item), value: (item) => item);

extension PlaceTypeDescriptor on PlaceType {
  String get value => toString();
}

extension PlaceTypeEnumParser on String {
  PlaceType? toPlaceType() {
    if (toUpperCase() == 'NULL') {
      return null;
    }
    return placeTypeValuesMap[this];
  }
}
