// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'place.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_Place _$PlaceFromJson(Map json) => _Place(
  id: json['id'] as String?,
  address: json['address'] as String?,
  addressComponents: (json['addressComponents'] as List<dynamic>?)
      ?.map(
        (e) => AddressComponent.fromJson(Map<String, Object?>.from(e as Map)),
      )
      .toList(),
  businessStatus: json['businessStatus'] == null
      ? null
      : BusinessStatus.fromJson(json['businessStatus'] as String),
  attributions: (json['attributions'] as List<dynamic>?)
      ?.map((e) => e as String)
      .toList(),
  latLng: json['latLng'] == null
      ? null
      : LatLng.fromJson(Map<String, Object?>.from(json['latLng'] as Map)),
  name: json['name'] as String?,
  nameLanguageCode: json['nameLanguageCode'] as String?,
  openingHours: json['openingHours'] == null
      ? null
      : OpeningHours.fromJson(
          Map<String, Object?>.from(json['openingHours'] as Map),
        ),
  phoneNumber: json['phoneNumber'] as String?,
  photoMetadatas: (json['photoMetadatas'] as List<dynamic>?)
      ?.map((e) => PhotoMetadata.fromJson(Map<String, Object?>.from(e as Map)))
      .toList(),
  plusCode: json['plusCode'] == null
      ? null
      : PlusCode.fromJson(Map<String, Object?>.from(json['plusCode'] as Map)),
  priceLevel: (json['priceLevel'] as num?)?.toInt(),
  rating: (json['rating'] as num?)?.toDouble(),
  types: (json['types'] as List<dynamic>?)
      ?.map((e) => PlaceType.fromJson(e as String))
      .toList(),
  userRatingsTotal: (json['userRatingsTotal'] as num?)?.toInt(),
  utcOffsetMinutes: (json['utcOffsetMinutes'] as num?)?.toInt(),
  viewport: json['viewport'] == null
      ? null
      : LatLngBounds.fromJson(
          Map<String, Object?>.from(json['viewport'] as Map),
        ),
  websiteUri: json['websiteUri'] == null
      ? null
      : Uri.parse(json['websiteUri'] as String),
  reviews: (json['reviews'] as List<dynamic>?)
      ?.map((e) => Review.fromJson(Map<String, Object?>.from(e as Map)))
      .toList(),
);

Map<String, dynamic> _$PlaceToJson(_Place instance) => <String, dynamic>{
  'id': instance.id,
  'address': instance.address,
  'addressComponents': instance.addressComponents
      ?.map((e) => e.toJson())
      .toList(),
  'businessStatus': _$BusinessStatusEnumMap[instance.businessStatus],
  'attributions': instance.attributions,
  'latLng': instance.latLng?.toJson(),
  'name': instance.name,
  'nameLanguageCode': instance.nameLanguageCode,
  'openingHours': instance.openingHours?.toJson(),
  'phoneNumber': instance.phoneNumber,
  'photoMetadatas': instance.photoMetadatas?.map((e) => e.toJson()).toList(),
  'plusCode': instance.plusCode?.toJson(),
  'priceLevel': instance.priceLevel,
  'rating': instance.rating,
  'types': instance.types?.map((e) => _$PlaceTypeEnumMap[e]!).toList(),
  'userRatingsTotal': instance.userRatingsTotal,
  'utcOffsetMinutes': instance.utcOffsetMinutes,
  'viewport': instance.viewport?.toJson(),
  'websiteUri': instance.websiteUri?.toString(),
  'reviews': instance.reviews?.map((e) => e.toJson()).toList(),
};

const _$BusinessStatusEnumMap = {
  BusinessStatus.Operational: 'OPERATIONAL',
  BusinessStatus.ClosedTemporarily: 'CLOSED_TEMPORARILY',
  BusinessStatus.ClosedPermanently: 'CLOSED_PERMANENTLY',
};

const _$PlaceTypeEnumMap = {
  PlaceType.OTHER: 'OTHER',
  PlaceType.ACCOUNTING: 'ACCOUNTING',
  PlaceType.ADMINISTRATIVE_AREA_LEVEL_1: 'ADMINISTRATIVE_AREA_LEVEL_1',
  PlaceType.ADMINISTRATIVE_AREA_LEVEL_2: 'ADMINISTRATIVE_AREA_LEVEL_2',
  PlaceType.ADMINISTRATIVE_AREA_LEVEL_3: 'ADMINISTRATIVE_AREA_LEVEL_3',
  PlaceType.ADMINISTRATIVE_AREA_LEVEL_4: 'ADMINISTRATIVE_AREA_LEVEL_4',
  PlaceType.ADMINISTRATIVE_AREA_LEVEL_5: 'ADMINISTRATIVE_AREA_LEVEL_5',
  PlaceType.ADMINISTRATIVE_AREA_LEVEL_6: 'ADMINISTRATIVE_AREA_LEVEL_6',
  PlaceType.ADMINISTRATIVE_AREA_LEVEL_7: 'ADMINISTRATIVE_AREA_LEVEL_7',
  PlaceType.AIRPORT: 'AIRPORT',
  PlaceType.AMUSEMENT_PARK: 'AMUSEMENT_PARK',
  PlaceType.AQUARIUM: 'AQUARIUM',
  PlaceType.ARCHIPELAGO: 'ARCHIPELAGO',
  PlaceType.ART_GALLERY: 'ART_GALLERY',
  PlaceType.ATM: 'ATM',
  PlaceType.BAKERY: 'BAKERY',
  PlaceType.BANK: 'BANK',
  PlaceType.BAR: 'BAR',
  PlaceType.BEAUTY_SALON: 'BEAUTY_SALON',
  PlaceType.BICYCLE_STORE: 'BICYCLE_STORE',
  PlaceType.BOOK_STORE: 'BOOK_STORE',
  PlaceType.BOWLING_ALLEY: 'BOWLING_ALLEY',
  PlaceType.BUS_STATION: 'BUS_STATION',
  PlaceType.CAFE: 'CAFE',
  PlaceType.CAMPGROUND: 'CAMPGROUND',
  PlaceType.CAR_DEALER: 'CAR_DEALER',
  PlaceType.CAR_RENTAL: 'CAR_RENTAL',
  PlaceType.CAR_REPAIR: 'CAR_REPAIR',
  PlaceType.CAR_WASH: 'CAR_WASH',
  PlaceType.CASINO: 'CASINO',
  PlaceType.CEMETERY: 'CEMETERY',
  PlaceType.CHURCH: 'CHURCH',
  PlaceType.CITY_HALL: 'CITY_HALL',
  PlaceType.CLOTHING_STORE: 'CLOTHING_STORE',
  PlaceType.COLLOQUIAL_AREA: 'COLLOQUIAL_AREA',
  PlaceType.CONTINENT: 'CONTINENT',
  PlaceType.CONVENIENCE_STORE: 'CONVENIENCE_STORE',
  PlaceType.COUNTRY: 'COUNTRY',
  PlaceType.COURTHOUSE: 'COURTHOUSE',
  PlaceType.DENTIST: 'DENTIST',
  PlaceType.DEPARTMENT_STORE: 'DEPARTMENT_STORE',
  PlaceType.DOCTOR: 'DOCTOR',
  PlaceType.DRUGSTORE: 'DRUGSTORE',
  PlaceType.ELECTRICIAN: 'ELECTRICIAN',
  PlaceType.ELECTRONICS_STORE: 'ELECTRONICS_STORE',
  PlaceType.EMBASSY: 'EMBASSY',
  PlaceType.ESTABLISHMENT: 'ESTABLISHMENT',
  PlaceType.FINANCE: 'FINANCE',
  PlaceType.FIRE_STATION: 'FIRE_STATION',
  PlaceType.FLOOR: 'FLOOR',
  PlaceType.FLORIST: 'FLORIST',
  PlaceType.FOOD: 'FOOD',
  PlaceType.FUNERAL_HOME: 'FUNERAL_HOME',
  PlaceType.FURNITURE_STORE: 'FURNITURE_STORE',
  PlaceType.GAS_STATION: 'GAS_STATION',
  PlaceType.GENERAL_CONTRACTOR: 'GENERAL_CONTRACTOR',
  PlaceType.GEOCODE: 'GEOCODE',
  PlaceType.GROCERY_OR_SUPERMARKET: 'GROCERY_OR_SUPERMARKET',
  PlaceType.GYM: 'GYM',
  PlaceType.HAIR_CARE: 'HAIR_CARE',
  PlaceType.HARDWARE_STORE: 'HARDWARE_STORE',
  PlaceType.HEALTH: 'HEALTH',
  PlaceType.HINDU_TEMPLE: 'HINDU_TEMPLE',
  PlaceType.HOME_GOODS_STORE: 'HOME_GOODS_STORE',
  PlaceType.HOSPITAL: 'HOSPITAL',
  PlaceType.INSURANCE_AGENCY: 'INSURANCE_AGENCY',
  PlaceType.INTERSECTION: 'INTERSECTION',
  PlaceType.JEWELRY_STORE: 'JEWELRY_STORE',
  PlaceType.LAUNDRY: 'LAUNDRY',
  PlaceType.LANDMARK: 'LANDMARK',
  PlaceType.LAWYER: 'LAWYER',
  PlaceType.LIBRARY: 'LIBRARY',
  PlaceType.LIGHT_RAIL_STATION: 'LIGHT_RAIL_STATION',
  PlaceType.LIQUOR_STORE: 'LIQUOR_STORE',
  PlaceType.LOCAL_GOVERNMENT_OFFICE: 'LOCAL_GOVERNMENT_OFFICE',
  PlaceType.LOCALITY: 'LOCALITY',
  PlaceType.LOCKSMITH: 'LOCKSMITH',
  PlaceType.LODGING: 'LODGING',
  PlaceType.MEAL_DELIVERY: 'MEAL_DELIVERY',
  PlaceType.MEAL_TAKEAWAY: 'MEAL_TAKEAWAY',
  PlaceType.MOSQUE: 'MOSQUE',
  PlaceType.MOVIE_RENTAL: 'MOVIE_RENTAL',
  PlaceType.MOVIE_THEATER: 'MOVIE_THEATER',
  PlaceType.MOVING_COMPANY: 'MOVING_COMPANY',
  PlaceType.MUSEUM: 'MUSEUM',
  PlaceType.NATURAL_FEATURE: 'NATURAL_FEATURE',
  PlaceType.NEIGHBORHOOD: 'NEIGHBORHOOD',
  PlaceType.NIGHT_CLUB: 'NIGHT_CLUB',
  PlaceType.PAINTER: 'PAINTER',
  PlaceType.PARK: 'PARK',
  PlaceType.PARKING: 'PARKING',
  PlaceType.PET_STORE: 'PET_STORE',
  PlaceType.PHARMACY: 'PHARMACY',
  PlaceType.PHYSIOTHERAPIST: 'PHYSIOTHERAPIST',
  PlaceType.PLACE_OF_WORSHIP: 'PLACE_OF_WORSHIP',
  PlaceType.PLUMBER: 'PLUMBER',
  PlaceType.PLUS_CODE: 'PLUS_CODE',
  PlaceType.POINT_OF_INTEREST: 'POINT_OF_INTEREST',
  PlaceType.POLICE: 'POLICE',
  PlaceType.POLITICAL: 'POLITICAL',
  PlaceType.POST_BOX: 'POST_BOX',
  PlaceType.POST_OFFICE: 'POST_OFFICE',
  PlaceType.POSTAL_CODE_PREFIX: 'POSTAL_CODE_PREFIX',
  PlaceType.POSTAL_CODE_SUFFIX: 'POSTAL_CODE_SUFFIX',
  PlaceType.POSTAL_CODE: 'POSTAL_CODE',
  PlaceType.POSTAL_TOWN: 'POSTAL_TOWN',
  PlaceType.PREMISE: 'PREMISE',
  PlaceType.PRIMARY_SCHOOL: 'PRIMARY_SCHOOL',
  PlaceType.REAL_ESTATE_AGENCY: 'REAL_ESTATE_AGENCY',
  PlaceType.RESTAURANT: 'RESTAURANT',
  PlaceType.ROOFING_CONTRACTOR: 'ROOFING_CONTRACTOR',
  PlaceType.ROOM: 'ROOM',
  PlaceType.ROUTE: 'ROUTE',
  PlaceType.RV_PARK: 'RV_PARK',
  PlaceType.SCHOOL: 'SCHOOL',
  PlaceType.SECONDARY_SCHOOL: 'SECONDARY_SCHOOL',
  PlaceType.SHOE_STORE: 'SHOE_STORE',
  PlaceType.SHOPPING_MALL: 'SHOPPING_MALL',
  PlaceType.SPA: 'SPA',
  PlaceType.STADIUM: 'STADIUM',
  PlaceType.STORAGE: 'STORAGE',
  PlaceType.STORE: 'STORE',
  PlaceType.STREET_ADDRESS: 'STREET_ADDRESS',
  PlaceType.STREET_NUMBER: 'STREET_NUMBER',
  PlaceType.SUBLOCALITY_LEVEL_1: 'SUBLOCALITY_LEVEL_1',
  PlaceType.SUBLOCALITY_LEVEL_2: 'SUBLOCALITY_LEVEL_2',
  PlaceType.SUBLOCALITY_LEVEL_3: 'SUBLOCALITY_LEVEL_3',
  PlaceType.SUBLOCALITY_LEVEL_4: 'SUBLOCALITY_LEVEL_4',
  PlaceType.SUBLOCALITY_LEVEL_5: 'SUBLOCALITY_LEVEL_5',
  PlaceType.SUBLOCALITY: 'SUBLOCALITY',
  PlaceType.SUBPREMISE: 'SUBPREMISE',
  PlaceType.SUBWAY_STATION: 'SUBWAY_STATION',
  PlaceType.SUPERMARKET: 'SUPERMARKET',
  PlaceType.SYNAGOGUE: 'SYNAGOGUE',
  PlaceType.TAXI_STAND: 'TAXI_STAND',
  PlaceType.TOURIST_ATTRACTION: 'TOURIST_ATTRACTION',
  PlaceType.TOWN_SQUARE: 'TOWN_SQUARE',
  PlaceType.TRAIN_STATION: 'TRAIN_STATION',
  PlaceType.TRANSIT_STATION: 'TRANSIT_STATION',
  PlaceType.TRAVEL_AGENCY: 'TRAVEL_AGENCY',
  PlaceType.UNIVERSITY: 'UNIVERSITY',
  PlaceType.VETERINARY_CARE: 'VETERINARY_CARE',
  PlaceType.ZOO: 'ZOO',
  PlaceType.AMERICAN_RESTAURANT: 'AMERICAN_RESTAURANT',
  PlaceType.DISCOUNT_STORE: 'DISCOUNT_STORE',
  PlaceType.ICE_CREAM_SHOP: 'ICE_CREAM_SHOP',
  PlaceType.SANDWICH_SHOP: 'SANDWICH_SHOP',
  PlaceType.AMUSEMENT_CENTER: 'AMUSEMENT_CENTER',
  PlaceType.DOG_PARK: 'DOG_PARK',
  PlaceType.INDIAN_RESTAURANT: 'INDIAN_RESTAURANT',
  PlaceType.SCHOOL_DISTRICT: 'SCHOOL_DISTRICT',
  PlaceType.ATHLETIC_FIELD: 'ATHLETIC_FIELD',
  PlaceType.ELECTRIC_VEHICLE_CHARGING_STATION:
      'ELECTRIC_VEHICLE_CHARGING_STATION',
  PlaceType.INDONESIAN_RESTAURANT: 'INDONESIAN_RESTAURANT',
  PlaceType.SEAFOOD_RESTAURANT: 'SEAFOOD_RESTAURANT',
  PlaceType.AUTO_PARTS_STORE: 'AUTO_PARTS_STORE',
  PlaceType.EVENT_VENUE: 'EVENT_VENUE',
  PlaceType.ITALIAN_RESTAURANT: 'ITALIAN_RESTAURANT',
  PlaceType.SKI_RESORT: 'SKI_RESORT',
  PlaceType.BANQUET_HALL: 'BANQUET_HALL',
  PlaceType.EXTENDED_STAY_HOTEL: 'EXTENDED_STAY_HOTEL',
  PlaceType.JAPANESE_RESTAURANT: 'JAPANESE_RESTAURANT',
  PlaceType.SPANISH_RESTAURANT: 'SPANISH_RESTAURANT',
  PlaceType.BARBECUE_RESTAURANT: 'BARBECUE_RESTAURANT',
  PlaceType.FARM: 'FARM',
  PlaceType.KOREAN_RESTAURANT: 'KOREAN_RESTAURANT',
  PlaceType.SPORTING_GOODS_STORE: 'SPORTING_GOODS_STORE',
  PlaceType.BARBER_SHOP: 'BARBER_SHOP',
  PlaceType.FARMSTAY: 'FARMSTAY',
  PlaceType.LEBANESE_RESTAURANT: 'LEBANESE_RESTAURANT',
  PlaceType.SPORTS_CLUB: 'SPORTS_CLUB',
  PlaceType.BED_AND_BREAKFAST: 'BED_AND_BREAKFAST',
  PlaceType.FAST_FOOD_RESTAURANT: 'FAST_FOOD_RESTAURANT',
  PlaceType.MARINA: 'MARINA',
  PlaceType.SPORTS_COMPLEX: 'SPORTS_COMPLEX',
  PlaceType.BRAZILIAN_RESTAURANT: 'BRAZILIAN_RESTAURANT',
  PlaceType.FERRY_TERMINAL: 'FERRY_TERMINAL',
  PlaceType.MARKET: 'MARKET',
  PlaceType.STEAK_HOUSE: 'STEAK_HOUSE',
  PlaceType.BREAKFAST_RESTAURANT: 'BREAKFAST_RESTAURANT',
  PlaceType.FITNESS_CENTER: 'FITNESS_CENTER',
  PlaceType.MEDICAL_LAB: 'MEDICAL_LAB',
  PlaceType.SUSHI_RESTAURANT: 'SUSHI_RESTAURANT',
  PlaceType.BRUNCH_RESTAURANT: 'BRUNCH_RESTAURANT',
  PlaceType.FRENCH_RESTAURANT: 'FRENCH_RESTAURANT',
  PlaceType.MEDITERRANEAN_RESTAURANT: 'MEDITERRANEAN_RESTAURANT',
  PlaceType.SWIMMING_POOL: 'SWIMMING_POOL',
  PlaceType.BUS_STOP: 'BUS_STOP',
  PlaceType.GIFT_SHOP: 'GIFT_SHOP',
  PlaceType.MEXICAN_RESTAURANT: 'MEXICAN_RESTAURANT',
  PlaceType.TAILOR: 'TAILOR',
  PlaceType.CAMPING_CABIN: 'CAMPING_CABIN',
  PlaceType.GOLF_COURSE: 'GOLF_COURSE',
  PlaceType.MIDDLE_EASTERN_RESTAURANT: 'MIDDLE_EASTERN_RESTAURANT',
  PlaceType.TELECOMMUNICATIONS_SERVICE_PROVIDER:
      'TELECOMMUNICATIONS_SERVICE_PROVIDER',
  PlaceType.CELL_PHONE_STORE: 'CELL_PHONE_STORE',
  PlaceType.GREEK_RESTAURANT: 'GREEK_RESTAURANT',
  PlaceType.MOTEL: 'MOTEL',
  PlaceType.THAI_RESTAURANT: 'THAI_RESTAURANT',
  PlaceType.CHILD_CARE_AGENCY: 'CHILD_CARE_AGENCY',
  PlaceType.GROCERY_STORE: 'GROCERY_STORE',
  PlaceType.NATIONAL_PARK: 'NATIONAL_PARK',
  PlaceType.TRANSIT_DEPOT: 'TRANSIT_DEPOT',
  PlaceType.CHINESE_RESTAURANT: 'CHINESE_RESTAURANT',
  PlaceType.GUEST_HOUSE: 'GUEST_HOUSE',
  PlaceType.PARK_AND_RIDE: 'PARK_AND_RIDE',
  PlaceType.TRUCK_STOP: 'TRUCK_STOP',
  PlaceType.COFFEE_SHOP: 'COFFEE_SHOP',
  PlaceType.HAIR_SALON: 'HAIR_SALON',
  PlaceType.PERFORMING_ARTS_THEATER: 'PERFORMING_ARTS_THEATER',
  PlaceType.TURKISH_RESTAURANT: 'TURKISH_RESTAURANT',
  PlaceType.COMMUNITY_CENTER: 'COMMUNITY_CENTER',
  PlaceType.HAMBURGER_RESTAURANT: 'HAMBURGER_RESTAURANT',
  PlaceType.PIZZA_RESTAURANT: 'PIZZA_RESTAURANT',
  PlaceType.VEGAN_RESTAURANT: 'VEGAN_RESTAURANT',
  PlaceType.CONSULTANT: 'CONSULTANT',
  PlaceType.HELIPORT: 'HELIPORT',
  PlaceType.PLAYGROUND: 'PLAYGROUND',
  PlaceType.VEGETARIAN_RESTAURANT: 'VEGETARIAN_RESTAURANT',
  PlaceType.CONVENTION_CENTER: 'CONVENTION_CENTER',
  PlaceType.HIKING_AREA: 'HIKING_AREA',
  PlaceType.PRESCHOOL: 'PRESCHOOL',
  PlaceType.VIETNAMESE_RESTAURANT: 'VIETNAMESE_RESTAURANT',
  PlaceType.COTTAGE: 'COTTAGE',
  PlaceType.HISTORICAL_LANDMARK: 'HISTORICAL_LANDMARK',
  PlaceType.PRIVATE_GUEST_ROOM: 'PRIVATE_GUEST_ROOM',
  PlaceType.VISITOR_CENTER: 'VISITOR_CENTER',
  PlaceType.COURIER_SERVICE: 'COURIER_SERVICE',
  PlaceType.HOME_IMPROVEMENT_STORE: 'HOME_IMPROVEMENT_STORE',
  PlaceType.RAMEN_RESTAURANT: 'RAMEN_RESTAURANT',
  PlaceType.WEDDING_VENUE: 'WEDDING_VENUE',
  PlaceType.CULTURAL_CENTER: 'CULTURAL_CENTER',
  PlaceType.HOSTEL: 'HOSTEL',
  PlaceType.RESORT_HOTEL: 'RESORT_HOTEL',
  PlaceType.WHOLESALER: 'WHOLESALER',
  PlaceType.DENTAL_CLINIC: 'DENTAL_CLINIC',
  PlaceType.HOTEL: 'HOTEL',
  PlaceType.REST_STOP: 'REST_STOP',
  PlaceType.ACAI_SHOP: 'ACAI_SHOP',
  PlaceType.ADVENTURE_SPORTS_CENTER: 'ADVENTURE_SPORTS_CENTER',
  PlaceType.AFGHANI_RESTAURANT: 'AFGHANI_RESTAURANT',
  PlaceType.AFRICAN_RESTAURANT: 'AFRICAN_RESTAURANT',
  PlaceType.AIRSTRIP: 'AIRSTRIP',
  PlaceType.AMPHITHEATRE: 'AMPHITHEATRE',
  PlaceType.APARTMENT_BUILDING: 'APARTMENT_BUILDING',
  PlaceType.APARTMENT_COMPLEX: 'APARTMENT_COMPLEX',
  PlaceType.ARENA: 'ARENA',
  PlaceType.ART_STUDIO: 'ART_STUDIO',
  PlaceType.ASIAN_GROCERY_STORE: 'ASIAN_GROCERY_STORE',
  PlaceType.ASIAN_RESTAURANT: 'ASIAN_RESTAURANT',
  PlaceType.ASTROLOGER: 'ASTROLOGER',
  PlaceType.AUDITORIUM: 'AUDITORIUM',
  PlaceType.BAGEL_SHOP: 'BAGEL_SHOP',
  PlaceType.BARBECUE_AREA: 'BARBECUE_AREA',
  PlaceType.BAR_AND_GRILL: 'BAR_AND_GRILL',
  PlaceType.BEACH: 'BEACH',
  PlaceType.BEAUTICIAN: 'BEAUTICIAN',
  PlaceType.BODY_ART_SERVICE: 'BODY_ART_SERVICE',
  PlaceType.BOTANICAL_GARDEN: 'BOTANICAL_GARDEN',
  PlaceType.BUDGET_JAPANESE_INN: 'BUDGET_JAPANESE_INN',
  PlaceType.BUFFET_RESTAURANT: 'BUFFET_RESTAURANT',
  PlaceType.BUTCHER_SHOP: 'BUTCHER_SHOP',
  PlaceType.CAFETERIA: 'CAFETERIA',
  PlaceType.CANDY_STORE: 'CANDY_STORE',
  PlaceType.CATERING_SERVICE: 'CATERING_SERVICE',
  PlaceType.CAT_CAFE: 'CAT_CAFE',
  PlaceType.CHILDRENS_CAMP: 'CHILDRENS_CAMP',
  PlaceType.CHIROPRACTOR: 'CHIROPRACTOR',
  PlaceType.CHOCOLATE_FACTORY: 'CHOCOLATE_FACTORY',
  PlaceType.CHOCOLATE_SHOP: 'CHOCOLATE_SHOP',
  PlaceType.COMEDY_CLUB: 'COMEDY_CLUB',
  PlaceType.CONCERT_HALL: 'CONCERT_HALL',
  PlaceType.CONDOMINIUM_COMPLEX: 'CONDOMINIUM_COMPLEX',
  PlaceType.CONFECTIONERY: 'CONFECTIONERY',
  PlaceType.CORPORATE_OFFICE: 'CORPORATE_OFFICE',
  PlaceType.CULTURAL_LANDMARK: 'CULTURAL_LANDMARK',
  PlaceType.CYCLING_PARK: 'CYCLING_PARK',
  PlaceType.DANCE_HALL: 'DANCE_HALL',
  PlaceType.DELI: 'DELI',
  PlaceType.DESSERT_RESTAURANT: 'DESSERT_RESTAURANT',
  PlaceType.DESSERT_SHOP: 'DESSERT_SHOP',
  PlaceType.DINER: 'DINER',
  PlaceType.DOG_CAFE: 'DOG_CAFE',
  PlaceType.DONUT_SHOP: 'DONUT_SHOP',
  PlaceType.FERRIS_WHEEL: 'FERRIS_WHEEL',
  PlaceType.FINE_DINING_RESTAURANT: 'FINE_DINING_RESTAURANT',
  PlaceType.FISHING_CHARTER: 'FISHING_CHARTER',
  PlaceType.FISHING_POND: 'FISHING_POND',
  PlaceType.FOOD_COURT: 'FOOD_COURT',
  PlaceType.FOOD_DELIVERY: 'FOOD_DELIVERY',
  PlaceType.FOOD_STORE: 'FOOD_STORE',
  PlaceType.FOOT_CARE: 'FOOT_CARE',
  PlaceType.GARDEN: 'GARDEN',
  PlaceType.GOVERNMENT_OFFICE: 'GOVERNMENT_OFFICE',
  PlaceType.HISTORICAL_PLACE: 'HISTORICAL_PLACE',
  PlaceType.HOUSING_COMPLEX: 'HOUSING_COMPLEX',
  PlaceType.ICE_SKATING_RINK: 'ICE_SKATING_RINK',
  PlaceType.INN: 'INN',
  PlaceType.INTERNATIONAL_AIRPORT: 'INTERNATIONAL_AIRPORT',
  PlaceType.INTERNET_CAFE: 'INTERNET_CAFE',
  PlaceType.JAPANESE_INN: 'JAPANESE_INN',
  PlaceType.JUICE_SHOP: 'JUICE_SHOP',
  PlaceType.KARAOKE: 'KARAOKE',
  PlaceType.MAKEUP_ARTIST: 'MAKEUP_ARTIST',
  PlaceType.MASSAGE: 'MASSAGE',
  PlaceType.MOBILE_HOME_PARK: 'MOBILE_HOME_PARK',
  PlaceType.MONUMENT: 'MONUMENT',
  PlaceType.NAIL_SALON: 'NAIL_SALON',
  PlaceType.NEIGHBORHOOD_POLICE_STATION: 'NEIGHBORHOOD_POLICE_STATION',
  PlaceType.OBSERVATION_DECK: 'OBSERVATION_DECK',
  PlaceType.OFF_ROADING_AREA: 'OFF_ROADING_AREA',
  PlaceType.OPERA_HOUSE: 'OPERA_HOUSE',
  PlaceType.PHILHARMONIC_HALL: 'PHILHARMONIC_HALL',
  PlaceType.PICNIC_GROUND: 'PICNIC_GROUND',
  PlaceType.PLANETARIUM: 'PLANETARIUM',
  PlaceType.PLAZA: 'PLAZA',
  PlaceType.PSYCHIC: 'PSYCHIC',
  PlaceType.PUB: 'PUB',
  PlaceType.PUBLIC_BATH: 'PUBLIC_BATH',
  PlaceType.PUBLIC_BATHROOM: 'PUBLIC_BATHROOM',
  PlaceType.RANCH: 'RANCH',
  PlaceType.ROLLER_COASTER: 'ROLLER_COASTER',
  PlaceType.SAUNA: 'SAUNA',
  PlaceType.SCULPTURE: 'SCULPTURE',
  PlaceType.SKATEBOARD_PARK: 'SKATEBOARD_PARK',
  PlaceType.SKIN_CARE_CLINIC: 'SKIN_CARE_CLINIC',
  PlaceType.SPORTS_ACTIVITY_LOCATION: 'SPORTS_ACTIVITY_LOCATION',
  PlaceType.SPORTS_COACHING: 'SPORTS_COACHING',
  PlaceType.STABLE: 'STABLE',
  PlaceType.STATE_PARK: 'STATE_PARK',
  PlaceType.SUMMER_CAMP_ORGANIZER: 'SUMMER_CAMP_ORGANIZER',
  PlaceType.TANNING_STUDIO: 'TANNING_STUDIO',
  PlaceType.TEA_HOUSE: 'TEA_HOUSE',
  PlaceType.TOUR_AGENCY: 'TOUR_AGENCY',
  PlaceType.TOURIST_INFORMATION_CENTER: 'TOURIST_INFORMATION_CENTER',
  PlaceType.VIDEO_ARCADE: 'VIDEO_ARCADE',
  PlaceType.WAREHOUSE_STORE: 'WAREHOUSE_STORE',
  PlaceType.WATER_PARK: 'WATER_PARK',
  PlaceType.WELLNESS_CENTER: 'WELLNESS_CENTER',
  PlaceType.WILDLIFE_PARK: 'WILDLIFE_PARK',
  PlaceType.WILDLIFE_REFUGE: 'WILDLIFE_REFUGE',
  PlaceType.WINE_BAR: 'WINE_BAR',
  PlaceType.YOGA_STUDIO: 'YOGA_STUDIO',
};
